apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: stunnel-conf
data:
  stunnel.conf: |-
    fips = no
    setuid = root
    setgid = root
    pid = /var/run/stunnel.pid
    debug = 7 
    delay = yes
    foreground = yes
    options = NO_SSLv2
    options = NO_SSLv3
    [redis-cli]
      client = yes
      accept = 127.0.0.1:6379
      connect = master.<blabla>.cache.amazonaws.com:6379
    [redis-cli-replica]
      client = yes
      accept = 127.0.0.1:6380
      connect = replica.<blabla>.cache.amazonaws.com:6379
  # stunnel.pem null to avoid bug
  stunnel.pem: "foobar"
